// Comprehensive Bangladesh Districts & Thanas Data with Bangla mappings & phonetic search

export const DISTRICT_BANGLA_MAP: Record<string, { bn: string; alt: string[] }> = {
    'Dhaka': { bn: 'ঢাকা', alt: ['dacca', 'dhaka', 'dhk', 'ঢাকা'] },
    'Gazipur': { bn: 'গাজীপুর', alt: ['gazipur', 'gajipur', 'গাজীপুর'] },
    'Narayanganj': { bn: 'নারায়ণগঞ্জ', alt: ['narayanganj', 'narayonganj', 'নারায়নগঞ্জ', 'নারায়ণগঞ্জ'] },
    'Tangail': { bn: 'টাঙ্গাইল', alt: ['tangail', 'টাঙ্গাইল', 'টাংগাইল'] },
    'Kishoreganj': { bn: 'কিশোরগঞ্জ', alt: ['kishoreganj', 'kishorganj', 'কিশোরগঞ্জ'] },
    'Manikganj': { bn: 'মানিকগঞ্জ', alt: ['manikganj', 'manikgonj', 'মানিকগঞ্জ'] },
    'Munshiganj': { bn: 'মুন্সিগঞ্জ', alt: ['munshiganj', 'munshigonj', 'মুন্সীগঞ্জ', 'মুন্সিগঞ্জ'] },
    'Narsingdi': { bn: 'নরসিংদী', alt: ['narsingdi', 'narsindi', 'নরসিংদী'] },
    'Faridpur': { bn: 'ফরিদপুর', alt: ['faridpur', 'foridpur', 'ফরিদপুর'] },
    'Gopalganj': { bn: 'গোপালগঞ্জ', alt: ['gopalganj', 'gopalgonj', 'গোপালগঞ্জ'] },
    'Madaripur': { bn: 'মাদারীপুর', alt: ['madaripur', 'মাদারীপুর', 'মাদারিপুর'] },
    'Rajbari': { bn: 'রাজবাড়ী', alt: ['rajbari', 'রাজবাড়ী', 'রাজবাড়ি'] },
    'Shariatpur': { bn: 'শরীয়তপুর', alt: ['shariatpur', 'soriatpur', 'শরীয়তপুর', 'শরীয়তপুর'] },
    'Chittagong': { bn: 'চট্টগ্রাম', alt: ['chattogram', 'chittagong', 'ctg', 'চট্টগ্রাম'] },
    "Cox's Bazar": { bn: 'কক্সবাজার', alt: ['coxs bazar', 'coxsbazar', 'coxs-bazar', 'কক্সবাজার'] },
    'Comilla': { bn: 'কুমিল্লা', alt: ['cumilla', 'comilla', 'কুমিল্লা'] },
    'Feni': { bn: 'ফেনী', alt: ['feni', 'ফেনী', 'ফেনি'] },
    'Brahmanbaria': { bn: 'ব্রাহ্মণবাড়িয়া', alt: ['brahmanbaria', 'b-baria', 'bbaria', 'ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'] },
    'Rangamati': { bn: 'রাঙ্গামাটি', alt: ['rangamati', 'রাঙ্গামাটি', 'রাঙামাটি'] },
    'Noakhali': { bn: 'নোয়াখালী', alt: ['noakhali', 'নোয়াখালী', 'নোয়াখালী'] },
    'Chandpur': { bn: 'চাঁদপুর', alt: ['chandpur', 'চাঁদপুর', 'চাদপুর'] },
    'Lakshmipur': { bn: 'লক্ষ্মীপুর', alt: ['lakshmipur', 'laxmipur', 'লক্ষ্মীপুর', 'লক্ষীপুর'] },
    'Khagrachhari': { bn: 'খাগড়াছড়ি', alt: ['khagrachhari', 'khagrachari', 'খাগড়াছড়ি', 'খাগড়াছড়ি'] },
    'Bandarban': { bn: 'বান্দরবান', alt: ['bandarban', 'বান্দরবান'] },
    'Rajshahi': { bn: 'রাজশাহী', alt: ['rajshahi', 'raj', 'রাজশাহী'] },
    'Bogra': { bn: 'বগুড়া', alt: ['bogura', 'bogra', 'বগুড়া', 'বগুড়া'] },
    'Pabna': { bn: 'পাবনা', alt: ['pabna', 'পাবনা'] },
    'Natore': { bn: 'নাটোর', alt: ['natore', 'নাটোর'] },
    'Sirajganj': { bn: 'সিরাজগঞ্জ', alt: ['sirajganj', 'sirajgonj', 'সিরাজগঞ্জ'] },
    'Naogaon': { bn: 'নওগাঁ', alt: ['naogaon', 'নওগাঁ', 'নওগা'] },
    'Joypurhat': { bn: 'জয়পুরহাট', alt: ['joypurhat', 'jaipurhat', 'জয়পুরহাট', 'জয়পুরহাট'] },
    'Chapai Nawabganj': { bn: 'চাঁপাইনবাবগঞ্জ', alt: ['chapai nawabganj', 'nawabganj', 'chapai', 'চাঁপাইনবাবগঞ্জ', 'চাপাইনবাবগঞ্জ'] },
    'Khulna': { bn: 'খুলনা', alt: ['khulna', 'খুলনা'] },
    'Jessore': { bn: 'যশোর', alt: ['jashore', 'jessore', 'যশোর'] },
    'Satkhira': { bn: 'সাতক্ষীরা', alt: ['satkhira', 'সাতক্ষীরা'] },
    'Bagerhat': { bn: 'বাগেরহাট', alt: ['bagerhat', 'বাগেরহাট'] },
    'Narail': { bn: 'নড়াইল', alt: ['narail', 'নড়াইল', 'নড়াইল'] },
    'Magura': { bn: 'মাগুরা', alt: ['magura', 'মাগুরা'] },
    'Meherpur': { bn: 'মেহেরপুর', alt: ['meherpur', 'মেহেরপুর'] },
    'Chuadanga': { bn: 'চুয়াডাঙ্গা', alt: ['chuadanga', 'চুয়াডাঙ্গা', 'চুয়াডাঙ্গা'] },
    'Kushtia': { bn: 'কুষ্টিয়া', alt: ['kushtia', 'কুষ্টিয়া', 'কুষ্টিয়া'] },
    'Jhenaidah': { bn: 'ঝিনাইদহ', alt: ['jhenaidah', 'jhenidah', 'ঝিনাইদহ'] },
    'Barisal': { bn: 'বরিশাল', alt: ['barishal', 'barisal', 'বরিশাল'] },
    'Patuakhali': { bn: 'পটুয়াখালী', alt: ['patuakhali', 'পটুয়াখালী', 'পটুয়াখালী'] },
    'Bhola': { bn: 'ভোলা', alt: ['bhola', 'ভোলা'] },
    'Pirojpur': { bn: 'পিরোজপুর', alt: ['pirojpur', 'পিরোজপুর'] },
    'Barguna': { bn: 'বরগুনা', alt: ['barguna', 'বরগুনা'] },
    'Jhalokati': { bn: 'ঝালকাঠি', alt: ['jhalokati', 'jhalakati', 'ঝালকাঠি'] },
    'Sylhet': { bn: 'সিলেট', alt: ['sylhet', 'সিলেট'] },
    'Moulvibazar': { bn: 'মৌলভীবাজার', alt: ['moulvibazar', 'moulvibazar', 'মৌলভীবাজার'] },
    'Habiganj': { bn: 'হবিগঞ্জ', alt: ['habiganj', 'habigonj', 'হবিগঞ্জ'] },
    'Sunamganj': { bn: 'সুনামগঞ্জ', alt: ['sunamganj', 'sunamgonj', 'সুনামগঞ্জ'] },
    'Rangpur': { bn: 'রংপুর', alt: ['rangpur', 'রংপুর'] },
    'Dinajpur': { bn: 'দিনাজপুর', alt: ['dinajpur', 'দিনাজপুর'] },
    'Gaibandha': { bn: 'গাইবান্ধা', alt: ['gaibandha', 'গাইবান্ধা'] },
    'Kurigram': { bn: 'কুড়িগ্রাম', alt: ['kurigram', 'কুড়িগ্রাম', 'কুড়িগ্রাম'] },
    'Nilphamari': { bn: 'নীলফামারী', alt: ['nilphamari', 'নীলফামারী', 'নীলফামারি'] },
    'Lalmonirhat': { bn: 'লালমনিরহাট', alt: ['lalmonirhat', 'লালমনিরহাট'] },
    'Thakurgaon': { bn: 'ঠাকুরগাঁও', alt: ['thakurgaon', 'ঠাকুরগাঁও', 'ঠাকুরগাও'] },
    'Panchagarh': { bn: 'পঞ্চগড়', alt: ['panchagarh', 'পঞ্চগড়', 'পঞ্চগড়'] },
    'Mymensingh': { bn: 'ময়মনসিংহ', alt: ['mymensingh', 'ময়মনসিংহ', 'ময়মনসিংহ'] },
    'Jamalpur': { bn: 'জামালপুর', alt: ['jamalpur', 'জামালপুর'] },
    'Netrokona': { bn: 'নেত্রকোণা', alt: ['netrokona', 'নেত্রকোণা', 'নেত্রকোনা'] },
    'Sherpur': { bn: 'শেরপুর', alt: ['sherpur', 'শেরপুর'] },
};

// Comprehensive Thana/Upazila Bangla Mappings
export const COMMON_THANA_BANGLA_MAP: Record<string, string> = {
    'Abhaynagar': 'অভয়নগর',
    'Adabor': 'আদাবর',
    'Adamdighi': 'আদমদিঘী',
    'Aditmari': 'আদিতমারী',
    'Agailjhara': 'আগৈলঝাড়া',
    'Airport': 'বিমানবন্দর',
    'Ajmiriganj': 'আজমিরীগঞ্জ',
    'Akbar Shah': 'আকবর শাহ',
    'Akhaura': 'আখাউড়া',
    'Akkelpur': 'আক্কেলপুর',
    'Alamdanga': 'আলমডাঙ্গা',
    'Alfadanga': 'আলফাডাঙ্গা',
    'Alikadam': 'আলীকদম',
    'Amtali': 'আমতলী',
    'Anwara': 'আনোয়ারা',
    'Araihazar': 'আড়াইহাজার',
    'Ashuganj': 'আশুগঞ্জ',
    'Assasuni': 'আশাশুনি',
    'Astagram': 'অষ্টগ্রাম',
    'Atgharia': 'আটঘরিয়া',
    'Atpara': 'আটপাড়া',
    'Atrai': 'আত্রাই',
    'Atwari': 'আটোয়ারী',
    'Babuganj': 'বাবুগঞ্জ',
    'Badalgachhi': 'বদলগাছী',
    'Badarganj': 'বদরগঞ্জ',
    'Badda': 'বাড্ডা',
    'Bagatipara': 'বাগাতিপাড়া',
    'Bagerhat Sadar': 'বাগেরহাট সদর',
    'Bagha': 'বাঘা',
    'Baghaichhari': 'বাঘাইছড়ি',
    'Bagherpara': 'বাঘারপাড়া',
    'Bagmara': 'বাগমারা',
    'Bahubal': 'বাহুবল',
    'Bajitpur': 'বাজিতপুর',
    'Bakalia': 'বাকলিয়া',
    'Bakerganj': 'বাকেরগঞ্জ',
    'Baksiganj': 'বকশীগঞ্জ',
    'Balaganj': 'বালাগঞ্জ',
    'Baliadangi': 'বালিয়াডাঙ্গী',
    'Baliakandi': 'বালিয়াকান্দি',
    'Bamna': 'বামনা',
    'Banani': 'বনানী',
    'Banaripara': 'বানারীপাড়া',
    'Bancharampur': 'বাঞ্ছারামপুর',
    'Bandar': 'বন্দর',
    'Bandarban Sadar': 'বান্দরবান সদর',
    'Bangshal': 'বংশাল',
    'Baniyachong': 'বানিয়াচং',
    'Banshkhali': 'বাঁশখালী',
    'Baraigram': 'বড়াইগ্রাম',
    'Barguna Sadar': 'বরগুনা সদর',
    'Barhatta': 'বারহাট্টা',
    'Barisal Sadar': 'বরিশাল সদর',
    'Barkal': 'বরকল',
    'Barlekha': 'বড়লেখা',
    'Barura': 'বরুড়া',
    'Basail': 'বাসাইল',
    'Bason': 'বাসন',
    'Batiaghata': 'বটিয়াঘাটা',
    'Bauphal': 'বাউফল',
    'Bayezid': 'বায়েজিদ',
    'Beanibazar': 'বিয়ানীবাজার',
    'Begumganj': 'বেগমগঞ্জ',
    'Belabo': 'বেলাবো',
    'Belaichhari': 'বিলাইছড়ি',
    'Belkuchi': 'বেলকুচি',
    'Bera': 'বেড়া',
    'Betagi': 'বেতাগী',
    'Bhairab': 'ভৈরব',
    'Bhaluka': 'ভালুকা',
    'Bhandaria': 'ভাণ্ডারিয়া',
    'Bhanga': 'ভাঙ্গা',
    'Bhangura': 'ভাঙ্গুড়া',
    'Bhashantek': 'ভাষানটেক',
    'Bhatara': 'ভাটারা',
    'Bhedarganj': 'ভেদরগঞ্জ',
    'Bheramara': 'ভেড়ামারা',
    'Bhola Sadar': 'ভোলা সদর',
    'Bholahat': 'ভোলাহাট',
    'Bhuapur': 'ভূঞাপুর',
    'Bhurungamari': 'ভুরুঙ্গামারী',
    'Bijoynagar': 'বিজয়নগর',
    'Biman Bandar': 'বিমান বন্দর',
    'Biral': 'বিরল',
    'Birampur': 'বিরামপুর',
    'Birganj': 'বীরগঞ্জ',
    'Bishwamvarpur': 'বিশ্বম্ভরপুর',
    'Bishwanath': 'বিশ্বনাথ',
    'Boalia': 'বোয়ালিয়া',
    'Boalkhali': 'বোয়ালখালী',
    'Boalmari': 'বোয়ালমারী',
    'Bochaganj': 'বোচাগঞ্জ',
    'Boda': 'বোদা',
    'Bogra Sadar': 'বগুড়া সদর',
    'Brahmanbaria Sadar': 'ব্রাহ্মণবাড়িয়া সদর',
    'Brahmanpara': 'ব্রাহ্মণপাড়া',
    'Burhanuddin': 'বোরহানউদ্দিন',
    'Burichang': 'বুড়িচং',
    'Cantonment': 'ক্যান্টনমেন্ট',
    'Chakaria': 'চকোরিয়া',
    'Chandanaish': 'চন্দনাইশ',
    'Chandgaon': 'চান্দগাঁও',
    'Chandina': 'চান্দিনা',
    'Chandpur Sadar': 'চাঁদপুর সদর',
    'Chandrima': 'চন্দ্রিমা',
    'Chapai Nawabganj Sadar': 'চাঁপাইনবাবগঞ্জ সদর',
    'Char Fasson': 'চরফ্যাশন',
    'Char Rajibpur': 'চর রাজিবপুর',
    'Charbhadrasan': 'চরভদ্রাসন',
    'Charghat': 'চারঘাট',
    'Chatkhil': 'চাটখিল',
    'Chatmohar': 'চাটমোহর',
    'Chauddagram': 'চৌদ্দগ্রাম',
    'Chaugachha': 'চৌগাছা',
    'Chauhali': 'চৌহালী',
    'Chawkbazar': 'চকবাজার',
    'Chhagalnaiya': 'ছাগলনাইয়্যা',
    'Chhatak': 'ছাতক',
    'Chilmari': 'চিলমারী',
    'Chirirbandar': 'চিরিরবন্দর',
    'Chitalmari': 'চিতলমারী',
    'Chittagong Sadar': 'চট্টগ্রাম সদর',
    'Chuadanga Sadar': 'চুয়াডাঙ্গা সদর',
    'Chunarughat': 'চুনারুঘাট',
    'Comilla Sadar': 'কুমিল্লা সদর',
    'Comilla Sadar Dakshin': 'কুমিল্লা সদর দক্ষিণ',
    'Companiganj': 'কোম্পানীগঞ্জ',
    'Dacope': 'দাকোপ',
    'Daganbhuiyan': 'দাগনভূঞা',
    'Dakshin Sunamganj (Shantiganj)': 'শান্তিগঞ্জ (দক্ষিণ সুনামগঞ্জ)',
    'Dakshinkhan': 'দক্ষিণখান',
    'Damudya': 'ডামুড্যা',
    'Damurhuda': 'দামুড়হুদা',
    'Darus Salam': 'দারুস সালাম',
    'Dasar': 'ডাসার',
    'Dashmina': 'দশমিনা',
    'Daudkandi': 'দাউদকান্দি',
    'Daulatkhan': 'দৌলতখান',
    'Daulatpur': 'দৌলতপুর',
    'Debhata': 'দেবহাটা',
    'Debidwar': 'দেবীদ্বার',
    'Debiganj': 'দেবীগঞ্জ',
    'Delduar': 'দেলদুয়ার',
    'Demra': 'ডেমরা',
    'Derai': 'দিরাই',
    'Dewanganj': 'দেওয়ানগঞ্জ',
    'Dhamoirhat': 'ধামইরহাট',
    'Dhamrai': 'ধামরাই',
    'Dhanbari': 'ধনবাড়ী',
    'Dhanmondi': 'ধানমন্ডি',
    'Dharamapasha': 'ধর্মপাশা',
    'Dhobaura': 'ধোবাউড়া',
    'Dhunat': 'ধুনট',
    'Dhupchanchia': 'দুপচাঁচিয়া',
    'Dighalia': 'দিঘলিয়া',
    'Dighinala': 'দিঘীনালা',
    'Dimla': 'ডিমলা',
    'Dinajpur Sadar': 'দিনাজপুর সদর',
    'Dohar': 'দোহার',
    'Domar': 'ডোমার',
    'Double Mooring': 'ডবলমুরিং',
    'Dowarabazar': 'দোয়ারাবাজার',
    'Dumki': 'দুমকি',
    'Dumuria': 'ডুমুরিয়া',
    'Durgapur': 'দুর্গাপুর',
    'Durgapur ': 'দুর্গাপুর',
    'Eidgaon': 'ঈদগাঁও',
    'EPZ': 'ইপিজেড',
    'Fakirhat': 'ফকিরহাট',
    'Faridganj': 'ফরিদগঞ্জ',
    'Faridpur Sadar': 'ফরিদপুর সদর',
    'Fatikchhari': 'ফটিকছড়ি',
    'Fatullah': 'ফতুল্লা',
    'Fenchuganj': 'ফেঞ্চুগঞ্জ',
    'Feni Sadar': 'ফেনী সদর',
    'Fulbaria': 'ফুলবাড়ীয়া',
    'Fulchhari': 'ফুলছড়ি',
    'Fulgazi': 'ফুলগাজী',
    'Gabtali': 'গাবতলী',
    'Gacha': 'গাছা',
    'Gaffargaon': 'গফরগাঁও',
    'Gaibandha Sadar': 'গাইবান্ধা সদর',
    'Galachipa': 'গলাচিপা',
    'Gangachhara': 'গঙ্গাচড়া',
    'Gangni': 'গাংনী',
    'Gauripur': 'গৌরীপুর',
    'Gaurnadi': 'গৌরনদী',
    'Gazaria': 'গজারিয়া',
    'Gazipur Sadar': 'গাজীপুর সদর',
    'Gendaria': 'গেন্ডারিয়া',
    'Ghatail': 'ঘাটাইল',
    'Ghior': 'ঘিওর',
    'Ghoraghat': 'ঘোড়াঘাট',
    'Goalandaghat': 'গোয়ালন্দঘাট',
    'Gobindaganj': 'গোবিন্দগঞ্জ',
    'Godagari': 'গোদাগাড়ী',
    'Golapganj': 'গোলাপগঞ্জ',
    'Gomastapur': 'গোমস্তাপুর',
    'Gopalganj Sadar': 'গোপালগঞ্জ সদর',
    'Gopalpur': 'গোপালপুর',
    'Gosairhat': 'গোসাইরহাট',
    'Gowainghat': 'গোয়াইনঘাট',
    'Guimara': 'গুইমারা',
    'Gulshan': 'গুলশান',
    'Gurudaspur': 'গুরুদাসপুর',
    'Habiganj Sadar': 'হবিগঞ্জ সদর',
    'Haimchar': 'হাইমচর',
    'Hakimpur': 'হাকিমপুর',
    'Halishahar': 'হালিশহর',
    'Haluaghat': 'হালুয়াঘাট',
    'Harinakunda': 'হরিণাকুণ্ডু',
    'Harintana': 'হরিণটানা',
    'Haripur': 'হরিপুর',
    'Harirampur': 'হরিরামপুর',
    'Hathazari': 'হাটহাজারী',
    'Hatibandha': 'হাতীবান্ধা',
    'Hatirjheel': 'হাতিরঝিল',
    'Hatiya': 'হাতিয়া',
    'Hazaribagh': 'হাজারীবাগ',
    'Haziganj': 'হাজীগঞ্জ',
    'Hizla': 'হিজলা',
    'Homna': 'হোমনা',
    'Hossainpur': 'হোসেনপুর',
    'Indurkani': 'ইন্দুরকানী',
    'Ishwardi': 'ঈশ্বরদী',
    'Ishwarganj': 'ঈশ্বরগঞ্জ',
    'Islampur': 'ইসলামপুর',
    'Itna': 'ইটনা',
    'Jagannathpur': 'জগন্নাথপুর',
    'Jaintiapur': 'জৈন্তাপুর',
    'Jalalabad': 'জালালাবাদ',
    'Jaldhaka': 'জলঢাকা',
    'Jamalganj': 'জামালগঞ্জ',
    'Jamalpur Sadar': 'জামালপুর সদর',
    'Jatrabari': 'যাত্রাবাড়ী',
    'Jessore Sadar': 'যশোর সদর',
    'Jhalokati Sadar': 'ঝালকাঠি সদর',
    'Jhenaidah Sadar': 'ঝিনাইদহ সদর',
    'Jhenaigati': 'ঝিনাইগাতী',
    'Jhikargachha': 'ঝিকরগাছা',
    'Jibannagar': 'জীবননগর',
    'Joypurhat Sadar': 'জয়পুরহাট সদর',
    'Juraichhari': 'জুরাইছড়ি',
    'Juri': 'জুড়ী',
    'Kabirhat': 'কবিরহাট',
    'Kachua': 'কচুয়া',
    'Kadamtali': 'কদমতলী',
    'Kafrul': 'কাফরুল',
    'Kahaloo': 'কাহালু',
    'Kaharole': 'কাহারোল',
    'Kalabagan': 'কলাবাগান',
    'Kalai': 'কালাই',
    'Kalapara': 'কলাপাড়া',
    'Kalaroa': 'কলারোয়া',
    'Kalia': 'কালিয়া',
    'Kaliakair': 'কালিয়াকৈর',
    'Kaliganj': 'কালীগঞ্জ',
    'Kalihati': 'কালিহাতী',
    'Kalkini': 'কালকিনি',
    'Kalmakanda': 'কলমাকান্দা',
    'Kalukhali': 'কালুখালী',
    'Kamalganj': 'কমলগঞ্জ',
    'Kamalnagar': 'কমলনগর',
    'Kamarkhanda': 'কামারখন্দ',
    'Kamrangirchar': 'কামরাঙ্গীরচর',
    'Kanaighat': 'কানাইঘাট',
    'Kapasia': 'কাপাসিয়া',
    'Kaptai': 'কাপ্তাই',
    'Karimganj': 'করিমগঞ্জ',
    'Karnafuli': 'কর্ণফুলী',
    'Kasba': 'কসবা',
    'Kashiadanga': 'কাশিয়াডাঙ্গা',
    'Kashiani': 'কাশিয়ানী',
    'Kashimpur': 'কাশিমপুর',
    'Katakhali': 'কাটাখালী',
    'Kathalia': 'কাঠালিয়া',
    'Katiadi': 'কটিয়াদী',
    'Kaunia': 'কাউনিয়া',
    'Kawkhali': 'কাউখালী',
    'Kazipur': 'কাজীপুর',
    'Kendua': 'কেন্দুয়া',
    'Keraniganj': 'কেরানীগঞ্জ',
    'Keshabpur': 'কেশবপুর',
    'Khagrachhari Sadar': 'খাগড়াছড়ি সদর',
    'Khaliajuri': 'খালিয়াজুড়ি',
    'Khalishpur': 'খালিশপুর',
    'Khan Jahan Ali': 'খান জাহান আলী',
    'Khansama': 'খানসামা',
    'Khetlal': 'খেতলাল',
    'Khilgaon': 'খিলগাঁও',
    'Khilkhet': 'খিলক্ষেত',
    'Khoksa': 'খোকসা',
    'Khulna Sadar': 'খুলনা সদর',
    'Khulshi': 'খুলশী',
    'Kishoreganj Sadar': 'কিশোরগঞ্জ সদর',
    'Konabari': 'কোনাবাড়ী',
    'Kotalipara': 'কোটালীপাড়া',
    'Kotchandpur': 'কোটচাঁদপুর',
    'Kotwali': 'কোতোয়ালী',
    'Koyra': 'কয়রা',
    'Kulaura': 'কুলাউড়া',
    'Kuliarchar': 'কুলিয়ারচর',
    'Kumarkhali': 'কুমারখালী',
    'Kurigram Sadar': 'কুড়িগ্রাম সদর',
    'Kushtia Sadar': 'কুষ্টিয়া সদর',
    'Kutubdia': 'কুতুবদিয়া',
    'Lakhai': 'লাখাই',
    'Laksam': 'লাকসাম',
    'Lakshmichhari': 'লক্ষ্মীছড়ি',
    'Lakshmipur Sadar': 'লক্ষ্মীপুর সদর',
    'Lalbagh': 'লালবাগ',
    'Lalmai': 'লালমাই',
    'Lalmohan': 'লালমোহন',
    'Lalmonirhat Sadar': 'লালমনিরহাট সদর',
    'Lalpur': 'লালপুর',
    'Lama': 'লামা',
    'Langadu': 'লংগদু',
    'Lohagara': 'লোহাগাড়া',
    'Louhajang': 'লৌহজং',
    'Madan': 'মদন',
    'Madarganj': 'মাদারগঞ্জ',
    'Madaripur Sadar': 'মাদারীপুর সদর',
    'Madhabpur': 'মাধবপুর',
    'Madhukhali': 'মধুখালী',
    'Madhupur': 'মধুপুর',
    'Madhyanagar': 'মধ্যনগর',
    'Magura Sadar': 'মাগুরা সদর',
    'Mahalchhari': 'মহালছড়ি',
    'Maheshkhali': 'মহেশখালী',
    'Maheshpur': 'মহেশপুর',
    'Manda': 'মান্দা',
    'Manikchhari': 'মানিকছড়ি',
    'Manikganj Sadar': 'মানিকগঞ্জ সদর',
    'Manirampur': 'মণিরামপুর',
    'Manpura': 'মনপুরা',
    'Mathbaria': 'মঠবাড়িয়া',
    'Matihar': 'মতিহার',
    'Matiranga': 'মাটিরাঙ্গা',
    'Matlab Dakshin': 'মতলব দক্ষিণ',
    'Matlab Uttar': 'মতলব উত্তর',
    'Meghna': 'মেঘনা',
    'Mehendiganj': 'মেহেন্দিগঞ্জ',
    'Meherpur Sadar': 'মেহেরপুর সদর',
    'Melandaha': 'মেলান্দহ',
    'Mirpur': 'মিরপুর',
    'Mirsharai': 'মীরসরাই',
    'Mirzaganj': 'মির্জাগঞ্জ',
    'Mirzapur': 'মির্জাপুর',
    'Mithamain': 'মিঠামইন',
    'Mithapukur': 'মিঠাপুকুর',
    'Moglabazar': 'মোগলাবাজার',
    'Mohadevpur': 'মহাদেবপুর',
    'Mohammadpur': 'মোহাম্মদপুর',
    'Mohanganj': 'মোহনগঞ্জ',
    'Mohanpur': 'মোহনপুর',
    'Mollahat': 'মোল্লাহাট',
    'Mongla': 'মোংলা',
    'Monohardi': 'মনোহরদী',
    'Monohargonj': 'মনোহরগঞ্জ',
    'Morrelganj': 'মোরেলগঞ্জ',
    'Motijheel': 'মতিঝিল',
    'Moulvibazar Sadar': 'মৌলভীবাজার সদর',
    'Mugda': 'মুগদা',
    'Mujibnagar': 'মুজিবনগর',
    'Muksudpur': 'মুকসুদপুর',
    'Muktagachha': 'মুক্তাগাছা',
    'Muladi': 'মুলাদী',
    'Munshiganj Sadar': 'মুন্সীগঞ্জ সদর',
    'Muradnagar': 'মুরাদনগর',
    'Mymensingh Sadar': 'ময়মনসিংহ সদর',
    'Nabiganj': 'নবীগঞ্জ',
    'Nabinagar': 'নবীনগর',
    'Nachole': 'নাচোল',
    'Nagarkanda': 'নগরকান্দা',
    'Nagarpur': 'নাগরপুর',
    'Nageshwari': 'নাগেশ্বরী',
    'Naikhongchhari': 'নাইক্ষ্যংছড়ি',
    'Nakla': 'নকলা',
    'Nalchity': 'নলছিটি',
    'Naldanga': 'নলডাঙ্গা',
    'Nalitabari': 'নালিতাবাড়ী',
    'Nandail': 'নান্দাইল',
    'Nandigram': 'নন্দীগ্রাম',
    'Nangalkot': 'নাঙ্গলকোট',
    'Naniarchar': 'নানিয়ারচর',
    'Naogaon Sadar': 'নওগাঁ সদর',
    'Narail Sadar': 'নড়াইল সদর',
    'Narayanganj Sadar': 'নারায়ণগঞ্জ সদর',
    'Naria': 'নড়িয়া',
    'Narsingdi Sadar': 'নরসিংদী সদর',
    'Nasirnagar': 'নাসিরনগর',
    'Natore Sadar': 'নাটোর সদর',
    'Nawabganj': 'নবাবগঞ্জ',
    'Nazirpur': 'নাজিরপুর',
    'Nesarabad (Swarupkati)': 'নেছারাবাদ (স্বরূপকাঠি)',
    'Netrokona Sadar': 'নেত্রকোণা সদর',
    'New Market': 'নিউ মার্কেট',
    'Niamatpur': 'নিয়ামতপুর',
    'Nikli': 'নিকলী',
    'Nilphamari Sadar': 'নীলফামারী সদর',
    'Noakhali Sadar': 'নোয়াখালী সদর',
    'Osmani Nagar': 'ওসমানী নগর',
    'Paba': 'পবা',
    'Pabna Sadar': 'পাবনা সদর',
    'Pahartali': 'পাহাড়তলী',
    'Paikgachha': 'পাইকগাছা',
    'Pakundia': 'পাকুন্দিয়া',
    'Palash': 'পলাশ',
    'Palashbari': 'পলাশবাড়ী',
    'Pallabi': 'পল্লবী',
    'Paltan': 'পল্টন',
    'Panchagarh Sadar': 'পঞ্চগড় সদর',
    'Panchbibi': 'পাঁচবিবি',
    'Panchhari': 'পানছড়ি',
    'Panchlaish': 'পাঁচলাইশ',
    'Pangsha': 'পাংশা',
    'Panthapath': 'পান্থপথ',
    'Parbatipur': 'পার্বতীপুর',
    'Parshuram': 'পরশুরাম',
    'Patenga': 'পতেঙ্গা',
    'Patgram': 'পাটগ্রাম',
    'Patharghata': 'পাথরঘাটা',
    'Patiya': 'পটিয়া',
    'Patnitala': 'পত্নীতলা',
    'Patuakhali Sadar': 'পটুয়াখালী সদর',
    'Pekua': 'পেকুয়া',
    'Phulpur': 'ফুলপুর',
    'Phultala': 'ফুলতলা',
    'Pirgachha': 'পীরগাছা',
    'Pirganj': 'পীরগঞ্জ',
    'Pirojpur Sadar': 'পিরোজপুর সদর',
    'Porsha': 'পোরশা',
    'Purbadhala': 'পূর্বধলা',
    'Puthia': 'পুঠিয়া',
    'Raiganj': 'রায়গঞ্জ',
    'Raipur': 'রায়পুর',
    'Raipura': 'রায়পুরা',
    'Rajapur': 'রাজাপুর',
    'Rajarhat': 'রাজারহাট',
    'Rajasthali': 'রাজস্থলী',
    'Rajbari Sadar': 'রাজবাড়ী সদর',
    'Rajnagar': 'রাজনগর',
    'Rajoir': 'রাজৈর',
    'Rajpara': 'রাজপাড়া',
    'Rajshahi Sadar': 'রাজশাহী সদর',
    'Ramganj': 'রামগঞ্জ',
    'Ramgarh': 'রামগড়',
    'Ramgati': 'রামগতি',
    'Ramna': 'রমনা',
    'Rampal': 'রামপাল',
    'Rampura': 'রামপুরা',
    'Ramu': 'রামু',
    'Rangabali': 'রাঙ্গাবালী',
    'Rangamati Sadar': 'রাঙ্গামাটি সদর',
    'Rangpur Sadar': 'রংপুর সদর',
    'Rangunia': 'রাঙ্গুনিয়া',
    'Raninagar': 'রাণীনগর',
    'Ranisankail': 'রাণীশংকৈল',
    'Raozan': 'রাউজান',
    'Routhmari': 'রৌমারী',
    'Rowangchhari': 'রোয়াংছড়ি',
    'Ruma': 'রুমা',
    'Rupganj': 'রূপগঞ্জ',
    'Rupnagar': 'রূপনগর',
    'Rupsha': 'রূপসা',
    'Sabujbagh': 'সবুজবাগ',
    'Sadarghat': 'সদরঘাট',
    'Sadarpur': 'সদরপুর',
    'Sadullapur': 'সাদুল্লাপুর',
    'Saidpur': 'সৈয়দপুর',
    'Sakhipur': 'সখিপুর',
    'Saltha': 'সালথা',
    'Sandwip': 'সন্দ্বীপ',
    'Santhia': 'সাঁথিয়া',
    'Sapahar': 'সাপাহার',
    'Sarail': 'সরাইল',
    'Sarankhola': 'শরণখোলা',
    'Sariakandi': 'সারিয়াকান্দি',
    'Sarishabari': 'সরিষাবাড়ী',
    'Satkania': 'সাতকানিয়া',
    'Satkhira Sadar': 'সাতক্ষীরা সদর',
    'Saturia': 'সাটুরিয়া',
    'Savar': 'সাভার',
    'Sayestaganj': 'শায়েস্তাগঞ্জ',
    'Senbagh': 'সেনবাগ',
    'Shah Ali': 'শাহ আলী',
    'Shah Makhdum': 'শাহ মখদুম',
    'Shah Paran': 'শাহপরাণ',
    'Shahbagh': 'শাহবাগ',
    'Shahjadpur': 'শাহজাদপুর',
    'Shahrasti': 'শাহরাস্তি',
    'Shailkupa': 'শৈলকুপা',
    'Shajahanpur': 'শাজাহানপুর',
    'Shalikha': 'শালিখা',
    'Shariatpur Sadar': 'শরীয়তপুর সদর',
    'Sharsha': 'শার্শা',
    'Sher-e-Bangla Nagar': 'শেরেবাংলা নগর',
    'Sherpur': 'শেরপুর',
    'Sherpur Sadar': 'শেরপুর সদর',
    'Shibalaya': 'শিবালয়',
    'Shibchar': 'শিবচর',
    'Shibganj': 'শিবগঞ্জ',
    'Shibpur': 'শিবপুর',
    'Shyamnagar': 'শ্যামনগর',
    'Shyampur': 'শ্যামপুর',
    'Siddhirganj': 'সিদ্ধিরগঞ্জ',
    'Singair': 'সিংগাইর',
    'Singra': 'সিংড়া',
    'Sirajdikhan': 'সিরাজদিখান',
    'Sirajganj Sadar': 'সিরাজগঞ্জ সদর',
    'Sitakunda': 'সীতাকুণ্ড',
    'Sonadanga': 'সোনাডাঙ্গা',
    'Sonagazi': 'সোনাগাজী',
    'Sonaimuri': 'সোনাইমুড়ী',
    'Sonargaon': 'সোনারগাঁও',
    'Sonatala': 'সোনাতলা',
    'South Surma': 'দক্ষিণ সুরমা',
    'Sreebardi': 'শ্রীবরদী',
    'Sreemangal': 'শ্রীমঙ্গল',
    'Sreenagar': 'শ্রীনগর',
    'Sreepur': 'শ্রীপুর',
    'Subarnachar': 'সুবর্ণচর',
    'Sughatta': 'সাঘাটা',
    'Sujanagar': 'সুজানগর',
    'Sullah': 'শাল্লা',
    'Sunamganj Sadar': 'সুনামগঞ্জ সদর',
    'Sundarganj': 'সুন্দরগঞ্জ',
    'Sutrapur': 'সূত্রাপুর',
    'Sylhet Sadar': 'সিলেট সদর',
    'Tahirpur': 'তাহিরপুর',
    'Tala': 'তালা',
    'Taltali': 'তালতলী',
    'Tangail Sadar': 'টাঙ্গাইল সদর',
    'Tanore': 'তানোর',
    'Taraganj': 'তারাগঞ্জ',
    'Tarail': 'তাড়াইল',
    'Tarakanda': 'তারাকান্দা',
    'Tarash': 'তাড়াশ',
    'Tazumuddin': 'তজুমদ্দিন',
    'Tejgaon': 'তেজগাঁও',
    'Tejgaon Industrial Area': 'তেজগাঁও শিল্পাঞ্চল',
    'Teknaf': 'টেকনাফ',
    'Terokhada': 'তেরখাদা',
    'Tetulia': 'তেঁতুলিয়া',
    'Thakurgaon Sadar': 'ঠাকুরগাঁও সদর',
    'Thanchi': 'থানচি',
    'Titas': 'তিতাস',
    'Tongi': 'টঙ্গী',
    'Tongi East': 'টঙ্গী পূর্ব',
    'Tongi West': 'টঙ্গী পশ্চিম',
    'Tongibari': 'টঙ্গীবাড়ী',
    'Trishal': 'ত্রিশাল',
    'Tungipara': 'টুঙ্গিপাড়া',
    'Turag': 'তুরাগ',
    'Ukhiya': 'উখিয়া',
    'Ulipur': 'উলিপুর',
    'Ullahpara': 'উল্লাপাড়া',
    'Uttar Khan': 'উত্তরখান',
    'Uttara': 'উত্তরা',
    'Uttara East': 'উত্তরা পূর্ব',
    'Uttara West': 'উত্তরা পশ্চিম',
    'Vatara': 'ভাটারা',
    'Wari': 'ওয়ারী',
    'Wazirpur': 'উজিরপুর',
    'Zakiganj': 'জকিগঞ্জ',
    'Zanjira': 'জাজিরা',
};

/**
 * Returns a display label combining English and Bangla.
 * e.g., "Mymensingh (ময়মনসিংহ)"
 */
export function getDistrictLabel(name: string): string {
    const info = DISTRICT_BANGLA_MAP[name];
    if (info?.bn) {
        return `${name} (${info.bn})`;
    }
    return name;
}

/**
 * Returns comprehensive search keywords for a district including
 * English, Bangla, and alternate spellings.
 */
export function getDistrictSearchKeywords(name: string): string {
    const info = DISTRICT_BANGLA_MAP[name];
    if (info) {
        return `${name} ${info.bn} ${info.alt.join(' ')}`;
    }
    return name;
}

/**
 * Returns a display label for a thana.
 * e.g., "Trishal (ত্রিশাল)"
 */
export function getThanaLabel(name: string): string {
    const bn = COMMON_THANA_BANGLA_MAP[name];
    if (bn) {
        return `${name} (${bn})`;
    }
    return name;
}

/**
 * Returns search keywords for a thana in both English and Bengali.
 * e.g., "Trishal ত্রিশাল trishal"
 */
export function getThanaSearchKeywords(name: string): string {
    const bn = COMMON_THANA_BANGLA_MAP[name];
    if (bn) {
        return `${name} ${bn} ${name.toLowerCase()}`;
    }
    return `${name} ${name.toLowerCase()}`;
}
